var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/impact/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gpr6gd._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_098emen.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rrm~-q._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tjh7.u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_impact_page_actions_0yldzgt.js")
R.m(91203)
module.exports=R.m(91203).exports
