var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/donate/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0heairb._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0xusxhh.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rrm~-q._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0tjh7.u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_donate_page_actions_0ee9zwl.js")
R.m(50658)
module.exports=R.m(50658).exports
